version: '3'
services:
  web:
    build: web
    ports:
      - 3000:3000
  api:
    build: Docker-main
    ports:
      - 9090:9090
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/
